---
title: "FinalAnalysis"
author: "Jasmine Hyppolite and Ryan Chung"
date: "12/14/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r Summary Statistics}
anti_a <- read_dta("data/anti_abort replication leg_party_compet 28Jan20.dta")
# Subsets of the data potentially for future use
women <- subset(anti_a, Female == 1)
men <- subset(anti_a, Female == 0)
republicans <- subset(anti_a, party == "R")
democrats <- subset(anti_a, party == "D")

# ideology scale summary 
summary(anti_a$np_score_2)

# population proportions of party and gender


table(anti_a$Female, anti_a$party)
prop.table(table(anti_a$Female, anti_a$party))

genderparty_table <- table("Female" = anti_a$Female, "Party" = anti_a$party)
gender_prop <- prop.table(table("Female" = anti_a$Female))
genderparty_prop <- round(prop.table(
        table("Sex and Party" = anti_a$gender_party))*100,
        digits = 2)
ipg8_prop <- round(prop.table(table("IPG8" = anti_a$IPG8))*100, digits = 2)

# Summary Statistics 

genderparty_table
gender_prop
genderparty_prop
ipg8_prop


# setting types within gender party so I can use this later
anti_a$gender_party <- NA
anti_a$gender_party[anti_a$Female == 1 & anti_a$party == "D"] <- "Dem. Woman"
anti_a$gender_party[anti_a$Female == 1 & anti_a$party == "R"] <- "Rep. Woman"
anti_a$gender_party[anti_a$Female == 0 & anti_a$party == "D"] <- "Dem. Man"
anti_a$gender_party[anti_a$Female == 0 & anti_a$party == "R"] <- "Rep. Man"
```

```{r}
gender_party_means <- tapply(anti_a$bin_anti_all, anti_a$gender_party, mean)
party_means <- tapply(anti_a$bin_anti_all, anti_a$party, mean)
NP_means <- tapply(anti_a$np_score_2, anti_a$gender_party, mean)
gender_party_means_2 <- tapply(anti_a$bin_anti_all, anti_a$IPG8, mean)

# Bar Plot for NP score distribution of voting for at least one anti-abortion bill
barplot(NP_means,
        main = "Distribution of NP Ideology Scores by Party and Gender",
        xlab = "Gender and Party",
        ylab = "NP Ideology Score",
        col = "dodgerblue",
        border = "white",
        ylim = c(0,5))

# Bar Plot for IPG8 score distribution of voting for at least one anti-abortion bill
barplot(gender_party_means_2,
        main = "Distribution of Voting for Anti-Abortion Bills by Gender and Composite Measure",
        names.arg = c("Cons RW", "Cons RM", "Mod-Lib RW", "Mod-Lib RM", "Mod-Cons DM", "Mod-Cons DW", "Lib DM", "Lib DW"),
        xlab = "Party and Gender",
        ylab = "Distribution",
        col = "steelblue2",
        border = "white",
        cex.names = 0.5,
        cex.main = 0.9)

# Further Breakdowns
a <- tapply(anti_a$bin_anti_womtot, anti_a$IPG8, mean)
barplot(a,
        main = "Distribution of Voting for Anti-Abortion Bills (Pro-Life, Pro-Woman)",
        names.arg = c("Cons RW", "Cons RM", "Mod-Lib RW", "Mod-Lib RM", "Mod-Cons DM", "Mod-Cons DW", "Lib DM", "Lib DW"),
        xlab = "Party and Gender",
        ylab = "Distribution",
        col = "mediumpurple",
        border = "white",
        cex.names = 0.5,
        cex.main = 0.9)

b <- tapply(anti_a$bin_anti_fetus, anti_a$IPG8, mean)
barplot(b,
        main = "Distribution of Voting for Anti-Abortion Bills (Fetal)",
        names.arg = c("Cons RW", "Cons RM", "Mod-Lib RW", "Mod-Lib RM", "Mod-Cons DM", "Mod-Cons DW", "Lib DM", "Lib DW"),
        xlab = "Party and Gender",
        ylab = "Distribution",
        col = "goldenrod3",
        border = "white",
        cex.names = 0.5,
        cex.main = 0.9)

c <- tapply(anti_a$bin_anti_relig, anti_a$IPG8, mean)
barplot(c,
        main = "Distribution of Voting for Anti-Abortion Bills (Religion)",
        names.arg = c("Cons RW", "Cons RM", "Mod-Lib RW", "Mod-Lib RM", "Mod-Cons DM", "Mod-Cons DW", "Lib DM", "Lib DW"),
        xlab = "Party and Gender",
        ylab = "Distribution",
        col = "firebrick",
        border = "white",
        cex.names = 0.5,
        cex.main = 0.9)

d <- tapply(anti_a$bin_pro_all, anti_a$IPG8, mean)
barplot(d,
        main = "Distribution of Voting for Pro-Abortion Bills",
        names.arg = c("Cons RW", "Cons RM", "Mod-Lib RW", "Mod-Lib RM", "Mod-Cons DM", "Mod-Cons DW", "Lib DM", "Lib DW"),
        xlab = "Party and Gender",
        ylab = "Distribution",
        col = "springgreen4",
        border = "white",
        cex.names = 0.5,
        cex.main = 0.9)


# Bar Plot for party distribution of voting for at least one anti-abortion bill
barplot(party_means,
        main = "Distribution of Anti-Abortion Bill Votes by Party",
        xlab = "Party",
        ylab = "Distribution",
        col = "indianred",
        border = "white")


# Boxplot for Ideology Score by Sex
boxplot(np_score_2 ~ Female, data = anti_a,
        names = c("Female", "Male"),
        ylab = "Ideology Score",
        xlab = "Sex",
        main = "Ideology Score by Sex",
        las = 1, col = "violetred2",
        frame = FALSE)
```



```{r Regressions}
female_all_fit <- lm(anti_a$bin_anti_all ~ anti_a$Female)
summary(female_all_fit)

np_all_fit <- lm(anti_a$bin_anti_all ~ anti_a$np_score_2)
summary(np_all_fit)

party_all_fit <- lm(anti_a$bin_anti_all ~ anti_a$party)
summary(party_all_fit)


female_all_interaction_fit <- lm(bin_anti_all ~ Female*competitive, data = anti_a)
summary(female_all_interaction_fit)
female_womtot_interaction_fit <- lm(bin_anti_womtot ~ Female*competitive, data = anti_a)
summary(female_womtot_interaction_fit)
female_fetus_interaction_fit <- lm(bin_anti_fetus ~ Female*competitive, data = anti_a)
summary(female_fetus_interaction_fit)
female_relig_interaction_fit <- lm(bin_anti_relig ~ Female*competitive, data = anti_a)
summary(female_relig_interaction_fit)

female_all_interaction_fit <- 
        lm(bin_anti_all ~ Female*competitive, data = anti_a)
summary(female_all_interaction_fit)
female_womtot_interaction_fit <- 
        lm(bin_anti_womtot ~ Female*competitive, data = anti_a)
summary(female_womtot_interaction_fit)
female_fetus_interaction_fit <- 
        lm(bin_anti_fetus ~ Female*competitive, data = anti_a)
summary(female_fetus_interaction_fit)
female_relig_interaction_fit <- 
        lm(bin_anti_relig ~ Female*competitive, data = anti_a)
summary(female_relig_interaction_fit)
complex <- 
        lm(anti_a$bin_anti_all ~ anti_a$party + 
                   anti_a$Female + anti_a$competitive)
summary(complex)
# dont know interpretation here tbh but I know we need one of this type 


#this will be important for knitting!

stargazer::stargazer(female_all_interaction_fit,
                     title = "Linear Regression Models for Sex and Competition's 
                     Effect on Voting for Anti-Abortion Bills",
                      covariate.labels = c("Covariate 1",
                                           "Covariate 2",
                                           "Covariate 3"),
                     dep.var.labels = "Informative name of the dependent variable",
                     header = FALSE)
stargazer::stargazer(female_fetus_interaction_fit,
                     title = "Linear Regression Models for Sex and Competition's 
                     Effect on Voting for Anti-Abortion Bills",
                      covariate.labels = c("Covariate 1",
                                           "Covariate 2",
                                           "Covariate 3"),
                     dep.var.labels = "Informative name of the dependent variable",
                     header = FALSE)

stargazer::stargazer(female_relig_interaction_fit,
                     title = "Linear Regression Models for Sex and Competition's 
                     Effect on Voting for Anti-Abortion Bills",
                      covariate.labels = c("Covariate 1",
                                           "Covariate 2",
                                           "Covariate 3"),
                     dep.var.labels = "Informative name of the dependent variable",
                     header = FALSE)

stargazer::stargazer(female_womtot_interaction_fit,
                     title = "Linear Regression Models for Sex and Competition's 
                     Effect on Voting for Anti-Abortion Bills",
                      covariate.labels = c("Covariate 1",
                                           "Covariate 2",
                                           "Covariate 3"),
                     dep.var.labels = "Informative name of the dependent variable",
                     header = FALSE)


stargazer::stargazer(complex,
                     title = "Linear Regression Models for Sex and Competition's 
                     Effect on Voting for Anti-Abortion Bills",
                     covariate.labels = c("Covariate 1",
                                          "Covariate 2",
                                          "Covariate 3"),
                     dep.var.labels = "Informative name of the dependent variable",
                     header = FALSE)

```



```{r Appendix}
hist(x = dem_fem$np_score_2, freq = FALSE,
     main = "Distribution of Ideology Scores for Democratic Females",
     xlab = "Ideology Score \n 0 (Most Liberal) - 7.259 (Most Conservative)")
hist(x = dem_male$np_score_2, freq = FALSE,
     main = "Distribution of Ideology Scores for Democratic Males",
     xlab = "Ideology Score \n 0 (Most Liberal) - 7.259 (Most Conservative)")
hist(x = rep_fem$np_score_2, freq = FALSE,
     main = "Distribution of Ideology Scores for Republican Females",
     xlab = "Ideology Score \n 0 (Most Liberal) - 7.259 (Most Conservative)")
hist(x = rep_male$np_score_2, freq = FALSE,
     main = "Distribution of Ideology Scores for Republican Males",
     xlab = "Ideology Score \n 0 (Most Liberal) - 7.259 (Most Conservative)")
hist(x = women$np_score_2, freq = FALSE,
     main = "Distribution of Ideology Scores for Female Legislators 1997-2012",
     xlab = "Ideology Score \n 0 (Most Liberal) - 7.259 (Most Conservative)")


barplot(gender_party_means,
        main = "Distribution of Voting for Anti-Abortion Bills by Gender and Party",
        xlab = "Party and Gender",
        ylab = "Distribution",
        col = "steelblue2",
        border = "white")



# What resonates most by gender? (unsure if these should be proportions 
# or probabilities)

gender_antiwom_fit<- lm(anti_a$bin_anti_womtot ~ anti_a$Female)
# Males are 2.3% more likely to have voted for an anti abortion 
# bill that was pro-woman and pro-life

gender_antirelig_fit <- lm(anti_a$bin_anti_relig ~ anti_a$Female)
# males are 1.7% more likely to have voted for an anti abortion bill 
# that adheres to a religious or moral issue frame

gender_antifetus_fit <- lm(anti_a$bin_anti_fetus ~ anti_a$Female)
#males are 1.3% more likely to have votes for an anti abortion bill that 
# adheres to a fetal centric issue frame


lm(anti_a$bin_anti_womtot ~ anti_a$np_score_2)
# if you increase the np score by one unit, the probability of voting for an 
# anti abortion bill would be a difference of 2.4 percentage points
# more conservative --> more likely to vote for a pro-life framed
# anit abortion bill than any other type of anti abortion bill

lm(anti_a$bin_anti_relig ~ anti_a$np_score_2)
# if you increase the np score by one unit, the probability of voting for an 
# anti abortion bill would be a difference of 1.5 percentage points

lm(anti_a$bin_anti_fetus ~ anti_a$np_score_2)
## if you increase the np score by one unit, the probability of voting for an 
# anti abortion bill would be a difference of 1.2 percentage points

lm(anti_a$bin_anti_relig ~ anti_a$party)
# r = 0.0248, is highest out of all parties, independent is slightly negative
# and d = .004485

lm(anti_a$bin_anti_fetus ~ anti_a$party)
# r = .020949, highest of all again, I is negative and d is positive but 
# closer to zero

lm(anti_a$bin_anti_womtot ~ anti_a$party)
# I = .039299, I is surprisingly the highest here, followed by R, and then D


complex <- lm(anti_a$bin_anti_all ~ anti_a$party + anti_a$Female + anti_a$competitive)
summary(complex)


score_all_interaction_fit <- lm(bin_anti_all ~ np_score_2*rep_control, data = anti_a)
score_all_interaction_fit
#Assuming Democratic control of the state house or a 50-50 split, a one unit increase in np score leads to around a 2.6 percentage point increase in the likelihood of sponsorship of at least one anti-abortion bill
#This is lower than the percentage point increase in the regression of just bin_anti_all on np_score_2

score_womtot_interaction_fit <- lm(bin_anti_womtot ~ np_score_2*rep_control, data = anti_a)
score_womtot_interaction_fit
score_fetus_interaction_fit <- lm(bin_anti_fetus ~ np_score_2*rep_control, data = anti_a)
score_fetus_interaction_fit
score_relig_interaction_fit <- lm(bin_anti_relig ~ np_score_2*rep_control, data = anti_a)
score_relig_interaction_fit
#Adding the interaction between np_score_2 and rep_control always decreases the likelihood of sponsorship of at least one anti-abortion bill, albeit to different extents

summary(lm(bin_anti_all ~ np_score_2*competitive, data = anti_a))
#very statistically significant interaction coefficient, and based on this and the last regression, competitive seems to be a pretty strong marker

summary(lm(bin_anti_all ~ competitive*party*Female, data = anti_a))
#don't know how we would incorporate this one, but it may be interesting to paint the narrative that Republican women in a competitive political environment are forced to vote a certain way by their party (or we can talk about them being the hidden majority because we typically conjure an image of white conservative men being resistant to social change)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
